apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: monitoring
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Rajesh Website</title>
      </head>
      <body>
        <h1>This is Rajesh website</h1>
        <p>Deployed on GKE using Kubernetes </p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: monitoring
  labels:
    app: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80

